[[redirects]]
  from = "https://forge.trade"
  to = "https://app.forge.trade"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop"