blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://t.me/ForgeDEX
    about: User support should be directed to our Telegram group.
  - name: List a token
    url: https://github.com/Forge-Trade/tokenlist
    about: Follow the instructions in the tokenlist repo to add an asset to Forge.
